### ISSUE TITLE
Add ability to get first and last values

### ISSUE THREAD

**Issue by wanclem** [rehacktive/waspdb#10]
Nice job guys...Waspdb is really great...Using it and is super fast..Pls can u add support for ability to immediately get the last and first values in a WaspHash? I mean without having to know the key before hand.

**Comment by rehacktive** [comment]
Hi, thanks :) unfortunately the feature you requested is not possible, the data inside the WaspHash is not sorted, so there's not "first" or "last".
You can retrieve the list of all the keys, sort them and then use the first/last to get the data.

**Comment by wanaclem** [comment]
Ok.Cool
