### ISSUE TITLE
Make the warning  "This version is NOT compatible with the previous one." stand out

### ISSUE THREAD

**Issue by oversecio** [rehacktive/waspdb#11]
Just ran into a serous mishap due to upgrading the waspDB in Oversec from 1.0 to 1.1.1

Unfortunately I didn't test the upgrade path for users with an existing DB on disk and also pushed the update for all users at once - had a lot of fun waking up this morning ;-)

All my fault probably, but in order for other users to not run into this, you should consider to make that warning stand out more!

(A change of this scale would have probably warranted a bump of the  major version to 2 as well )

**Comment by rehacktive** [comment]
I'm really sorry about that. It was a very unexpected bug related to Android N and I pushed the release, just changing the version on the main README.
I'll add a warning on it.
I hope everything is ok with your project - that btw is very cool.
