### ISSUE TITLE
Model changes

### ISSUE THREAD

**Issue by pedrohenriquerls** [rehacktive/waspdb#9]
How can I do with model changes? If I change my model attributes waspDb will still working without migrations?

**Comment by stefanoqredo** [comment]
There's no "schema", so technically there's no migration.
If you change your model, you can't expect to read a different object from a previously (different) stored one.

I suggest in this case to do a "migration" procedure, retrieving previously stored objects, changing them to the new ones and store the new objects again.

**Comment by rehacktive** [comment]
There's no "schema", so technically there's no migration.
If you change your model, you can't expect to read a different object from a previously (different) stored one.

I suggest in this case to do a "migration" procedure, retrieving previously stored objects, changing them to the new ones and store the new objects again.

**Comment by pedrohenriquerls** [comment]
great thanks a lot :+1:
